// Given an array, write a loop to find the string 'zoqdub', print its index,
// and print how many iterations it took to find it.

const arr = [
  "avrgpy",
  "bllyxk",
  "bozbvwsw",
  "buqa",
  "cheddpyu",
  "coxsqclbk",
  "crhyyjn",
  "cvzcjev",
  "dbafkvcgvv",
  "diphtwtsl",
  "dqs",
  "eagxadgbe",
  "edkrmoni",
  "ejpqfy",
  "ekgvp",
  "etf",
  "fil",
  "fubi",
  "fwuegsiak",
  "fxlt",
  "fzv",
  "gdcpdsmv",
  "gdry",
  "giqqzgd",
  "gwva",
  "hrl",
  "huervuaz",
  "ivedjo",
  "iwsv",
  "izrap",
  "jazaxvqicd",
  "jbacwy",
  "jhxgujryq",
  "kdbecrgrnj",
  "khlqo",
  "kiqxvbbfcf",
  "kpyp",
  "lllvv",
  "mnwjsax",
  "mpkaqpisb",
  "mprzov",
  "mwidhb",
  "mxy",
  "niiv",
  "nkhm",
  "ocjw",
  "ovbe",
  "pdrywjcz",
  "pjla",
  "pyrrawu",
  "qaszjnrcs",
  "qbaewosypu",
  "qhtzzynxwf",
  "qkzdslj",
  "qmd",
  "qqjumq",
  "raeilugdhu",
  "ralfyer",
  "rebeiw",
  "riqjiavc",
  "rkjqao",
  "rmih",
  "rusgsxw",
  "scqs",
  "sdnipf",
  "sdpmhew",
  "shgrjjre",
  "sjlr",
  "snlr",
  "sro",
  "sul",
  "suumezsppo",
  "tggvi",
  "tiuborrfw",
  "tpydfr",
  "tsdt",
  "tzcrzruv",
  "ubfzml",
  "ugkeexldad",
  "ugmavm",
  "ujxm",
  "ulosh",
  "ultfyt",
  "untczjd",
  "utmy",
  "uxkmnnsf",
  "vcpzcqqmj",
  "veosegfto",
  "vftgjo",
  "vluuirir",
  "wifgbhdix",
  "woya",
  "xqfvc",
  "xvgssiad",
  "yccgr",
  "yejuswh",
  "zgw",
  "zlz",
  "zoqdub",
  "zxjmglvfy",
];

// Your code here

//Output examples
// index: 78 ---> this is the index of the string 'zoqdub'
// loopCount: 79 ---> this is the number of iterations it took to find the string 'zoqdub'

// You may need to use console logs like these within you code
// console.log(`index: ${index}`);
// console.log(`loopCount: ${loopCount}`);

// index: undefined
// loopCount: 100
